### ISSUE TITLE
CODE: check out requirements for Google Places API and Document

### ISSUE THREAD

**Issue by Skovvuri** [Skovvuri/travel-mate#11]

**Comment by unicorn453** [comment]
"https://maps.googleapis.com/maps/api/place/textsearch/json?query=${type}+in+${city}&key=${apiKey}"

https://developers.google.com/maps/documentation/places/web-service/search-text

**Comment by unicorn453** [comment]
Google Places API set up video: https://www.youtube.com/watch?v=Tva5HvZLN7g

**Comment by Skovvuri** [comment]
https://docs.google.com/document/d/e/2PACX-1vRwEDij3V_fCV-QZcadeg0DObMiITntoEz3RPQv5t7yieMfimwuY1xAaOsS4arP2ahKOVzdwUFohiSP/pub

published link we will be adding to to this. As we go.
