### ISSUE TITLE
CODE: Autocomplete feature using Local Storage

### ISSUE THREAD

**Issue by Skovvuri** [Skovvuri/travel-mate#18]

**Comment by Volodymyr-Shtyka** [comment]
Made Autocomplete feature without using Local Storage

**Comment by Volodymyr-Shtyka** [comment]
Made Autocomplete feature using Local Storage in the Issue: "Add the saved in localStorage cities to the autofill feature.
[#43](https://github.com/Skovvuri/travel-mate/issues/43)". I think this issue is no longer needed.
